language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dkssudvn2@gmail.com

# 배포 파일 관리
before_deploy:
  - zip -r alphabet-springboot-webservice *
  - mkdir -p deploy
  - mv alphabet-springboot-webservice.zip deploy/alphabet-springboot-webservice.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: alphabet-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
